// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spv-landing/AsymmetricGrid.tsx": () => import("../components/mockups/spv-landing/AsymmetricGrid.tsx"),
  "./components/mockups/spv-landing/DarkEditorial.tsx": () => import("../components/mockups/spv-landing/DarkEditorial.tsx"),
  "./components/mockups/spv-landing/DenseHorizontal.tsx": () => import("../components/mockups/spv-landing/DenseHorizontal.tsx"),
  "./components/mockups/spv-landing/IceArchitecture.tsx": () => import("../components/mockups/spv-landing/IceArchitecture.tsx"),
  "./components/mockups/spv-landing/Manifesto.tsx": () => import("../components/mockups/spv-landing/Manifesto.tsx"),
  "./components/mockups/spv-landing/StoneCopper.tsx": () => import("../components/mockups/spv-landing/StoneCopper.tsx")
};
